"""Add mnemonic_cache table

Revision ID: 3670a29c6612
Revises: 1c0d9e70d3ca
Create Date: 2025-12-08 16:07:39.149169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3670a29c6612'
down_revision: Union[str, Sequence[str], None] = '1c0d9e70d3ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mnemonic_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('definition_hash', sa.String(length=64), nullable=False),
    sa.Column('mnemonic_word', sa.Text(), nullable=False),
    sa.Column('mnemonic_sentence', sa.Text(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_hash', 'language', 'definition_hash', name='uq_mnemonic_cache')
    )
    op.create_index('idx_word_lang_def', 'mnemonic_cache', ['word_hash', 'language', 'definition_hash'], unique=False)
    op.create_index(op.f('ix_mnemonic_cache_definition_hash'), 'mnemonic_cache', ['definition_hash'], unique=False)
    op.create_index(op.f('ix_mnemonic_cache_id'), 'mnemonic_cache', ['id'], unique=False)
    op.create_index(op.f('ix_mnemonic_cache_word_hash'), 'mnemonic_cache', ['word_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mnemonic_cache_word_hash'), table_name='mnemonic_cache')
    op.drop_index(op.f('ix_mnemonic_cache_id'), table_name='mnemonic_cache')
    op.drop_index(op.f('ix_mnemonic_cache_definition_hash'), table_name='mnemonic_cache')
    op.drop_index('idx_word_lang_def', table_name='mnemonic_cache')
    op.drop_table('mnemonic_cache')
    # ### end Alembic commands ###
